language: php
php:
  - 5.3
  - 5.4

env:
  - DB=mysql

branches:
  only:
    - master
    - TYPO3_4-7

before_script:
# Install build dependencies
  - git clone git://github.com/typo3-ci/TYPO3-Travis-Integration.git build-environment
  - source build-environment/install-helper.sh
  - installPhpModule igbinary
  - installPhpModule -y memcache
  - installPhpModule redis
  - if [[ "$TRAVIS_PHP_VERSION" == "5.3" ]]; then installPhpModule -y apc; fi

# Install rudimentary TYPO3
  - git clone git://git.typo3.org/TYPO3v4/Distributions/Introduction.git build-environment/Introduction
  - mv build-environment/typo3conf .
  - git clone git://git.typo3.org/TYPO3v4/Extensions/phpunit.git typo3conf/ext/phpunit/
  - mkdir fileadmin
  - ln -s $PWD typo3_src
  - if [[ "$DB" == "mysql" ]]; then mysql -e "DROP DATABASE IF EXISTS typo3_test;" -uroot; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS typo3_test;" -uroot; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -uroot typo3_test < build-environment/Introduction/typo3conf/ext/introduction/Resources/Private/Subpackages/Introduction/Database/introduction.sql; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -uroot typo3_test < build-environment/dbimport/cli_users.sql; fi

script: php $PWD/typo3/cli_dispatch.phpsh phpunit $PWD/tests/
