language: php
php:
  - 5.3
  - 5.4
  - 5.5

env:
  - DB=mysql

services:
  - memcached

before_script:
# Install build dependencies
  - git clone git://github.com/typo3-ci/TYPO3-Travis-Integration.git build-environment
  - source build-environment/install-helper.sh
  - if [[ "$TRAVIS_PHP_VERSION" != "5.5" ]]; then installPhpModule igbinary; fi
  - installPhpModule -y memcache
  - installPhpModule redis
  - if [[ "$TRAVIS_PHP_VERSION" == "5.3" ]]; then installPhpModule -y apc; fi

# Install rudimentary TYPO3
  - git clone git://git.typo3.org/TYPO3v4/Distributions/Introduction.git build-environment/Introduction
  - mv build-environment/typo3conf .
  - git clone git://git.typo3.org/TYPO3v4/Extensions/phpunit.git typo3conf/ext/phpunit/
  - mkdir fileadmin
  - mkdir uploads
  - if [[ "$DB" == "mysql" ]]; then mysql -e "DROP DATABASE IF EXISTS typo3_test;" -uroot; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS typo3_test;" -uroot; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -uroot typo3_test < build-environment/Introduction/typo3conf/ext/introduction/Resources/Private/Subpackages/Introduction/Database/introduction.sql; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -uroot typo3_test < build-environment/dbimport/cache_tables.sql; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -uroot typo3_test < build-environment/dbimport/cli_users.sql; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -uroot typo3_test < build-environment/dbimport/phpunit.sql; fi

script:
  - phpLint all
  - php $PWD/typo3/cli_dispatch.phpsh phpunit -c typo3/sysext/core/Build/UnitTests.xml
