language: php

matrix:
  fast_finish: true
  allow_failures:
    - php: 7

  include:
    - php: 5.5
      env: UNIT_TESTS=yes FUNCTIONAL_TESTS=yes PHP_LINT=yes XLF_CHECK=yes SUBMODULE_TEST=yes
    - php: 5.6
      env: UNIT_TESTS=yes FUNCTIONAL_TESTS=yes PHP_LINT=yes
    - php: 7
      env: UNIT_TESTS=yes

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

services:
  - memcached
  - redis-server

notifications:
  irc:
    channels:
      - "irc.freenode.net#typo3-cms"
    on_success: change
    on_failure: always
    use_notice: true
  slack:
    rooms:
      secure: nHWVTPyG3CQWIcYA1LASS11dD0/NBcmrAyr3xxQW0XYtH47ZUKRlEtxrVLuL7ptciNwMbfZgsiRQ1QGWDerHUlBkg0iwRxpUZgeylzWaiXsHFVAp2IBfEX54KrWeYm9gewIBDDtnp+sLgpXGgmpIs2bAGkZe5129UsUExoWh0+g=
    on_success: change
    on_failure: always

before_script:
  - mkdir parallel && cd parallel && wget http://ftp.gnu.org/gnu/parallel/parallel-latest.tar.bz2 && tar xvf parallel-latest.tar.bz2 -C . --strip-components=1 && ./configure && make && cd ..
  - if [ -e ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini ]; then echo "extension = memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - if [ -e ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini ]; then echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - rm -rf typo3/sysext/compatibility6
  - composer install

script:
  - >
    if [[ "$UNIT_TESTS" == "yes" ]]; then
      echo;
      echo "Running unit tests";
      ./bin/phpunit --colors -c typo3/sysext/core/Build/UnitTests.xml
    fi
  - >
    if [[ "$FUNCTIONAL_TESTS" == "yes" ]]; then
        echo;
        export typo3DatabaseName="typo3";
        export typo3DatabaseHost="localhost";
        export typo3DatabaseUsername="root";
        export typo3DatabasePassword="";
        find . -wholename '*typo3/sysext/*/Tests/Functional/*Test.php' | ./parallel/src/parallel --gnu --will-cite 'echo; echo "Running functional test suite {}"; ./bin/phpunit --colors -c typo3/sysext/core/Build/FunctionalTests.xml {}'
    fi
  - >
    if [[ "$PHP_LINT" == "yes" ]]; then
        echo;
        echo "Running php lint";
        find typo3/ -name \*.php -not -path "typo3/contrib/vendor/*" | ./parallel/src/parallel --gnu --will-cite php -d display_errors=stderr -l {} > /dev/null \;
    fi
  - >
    if [[ "$XLF_CHECK" == "yes" ]]; then
        echo;
        echo "Running XLF checker";
        ./typo3/sysext/core/Build/Scripts/xlfcheck.sh
    fi
  - >
      if [[ "$SUBMODULE_TEST" == "yes" ]]; then
          echo;
          echo "Running git submodule check";
          /bin/bash -c "
              if [[ `git submodule status 2>&1 | wc -l` -ne 0 ]]; then
                  echo \"Found a submodule definition in repository\";
                  exit 99;
              fi
          "
      fi
