services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TYPO3\CMS\Redirects\:
    resource: '../Classes/*'

  TYPO3\CMS\Redirects\Controller\RecordHistoryRollbackController:
    tags: ['backend.controller']

  TYPO3\CMS\Redirects\Controller\ManagementController:
    tags: ['backend.controller']

  TYPO3\CMS\Redirects\Hooks\DataHandlerSlugUpdateHook:
    public: true

  TYPO3\CMS\Redirects\Command\CheckIntegrityCommand:
    tags:
      - name: 'console.command'
        command: 'redirects:checkintegrity'
        description: 'Check integrity of redirects'

  TYPO3\CMS\Redirects\Command\CleanupRedirectsCommand:
    tags:
      - name: 'console.command'
        command: 'redirects:cleanup'
        description: 'Cleanup old redirects periodically for given constraints like days, hit count or domains.'

  TYPO3\CMS\Redirects\EventListener\RecordHistoryRollbackEventsListener:
    tags:
      - name: event.listener
        identifier: 'redirects-disable-hook'
        method: 'beforeHistoryRollbackStartEvent'
      - name: event.listener
        identifier: 'redirects-enable-hook'
        method: 'afterHistoryRollbackFinishedEvent'
