services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TYPO3\CMS\IndexedSearch\:
    resource: '../Classes/*'

  TYPO3\CMS\IndexedSearch\Service\DatabaseSchemaService:
    tags:
      - name: event.listener
        identifier: 'indexed-search'
        method: 'addMysqlFulltextIndex'
