language: php

php:
  - 5.5
  - 5.6

env:
  - DB=mysql

before_script:
  - sudo apt-get install parallel
  - composer self-update
  - cd ..
  - git clone --single-branch --branch master --depth 1 https://github.com/TYPO3/TYPO3.CMS.git typo3_core
  - mv typo3_core/* .
  - composer install
  - mkdir -p typo3conf/ext
  - mv TYPO3.CMS.Styleguide typo3conf/ext/styleguide

script:
  - >
    echo;
    echo "Running unit tests";
    ./bin/phpunit --colors -c typo3/sysext/core/Build/UnitTests.xml typo3conf/ext/styleguide/Tests/Unit/
  - >
    echo;
    echo "Running php lint";
    find typo3conf/ext/styleguide/ -name \*.php | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
