categories:
  camino: ~

settings:
  camino.colorScheme:
    default: theme-caramel-cream
    type: string
    enum:
      theme-caramel-cream: 'Caramel Cream'
      theme-ocean-breeze: 'Ocean Breeze'
      theme-forest-mist: 'Forest Mist'
      theme-violet-velvet: 'Violet Velvet'
    category: camino
  camino.header.fixedPosition:
    default: false
    type: bool
    category: camino
