services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TYPO3\CMS\Backend\:
    resource: '../Classes/*'

  TYPO3\CMS\Backend\Command\ResetPasswordCommand:
    tags:
      - { name: 'console.command', command: 'backend:resetpassword', description: 'Trigger a password reset for a backend user', schedulable: false }

  TYPO3\CMS\Backend\Command\CreateBackendUserCommand:
    tags:
      - { name: 'console.command', command: 'backend:user:create', description: 'Create a backend user', schedulable: false }

  TYPO3\CMS\Backend\Middleware\ContentSecurityPolicyHeaders:
    arguments:
      $cache: '@cache.assets'

  TYPO3\CMS\Backend\Backend\Avatar\Avatar:
    public: true
    arguments:
      $cache: '@cache.runtime'

  TYPO3\CMS\Backend\Authentication\PasswordReset:
    public: true

  TYPO3\CMS\Backend\Clipboard\Clipboard:
    shared: false
    public: true

  TYPO3\CMS\Backend\ContextMenu\ContextMenu:
    public: true

  TYPO3\CMS\Backend\ContextMenu\ItemProviders\ItemProvidersRegistry:
    arguments:
      - !tagged_iterator backend.contextmenu.itemprovider

  # ModuleTemplate instantiated using factory.
  TYPO3\CMS\Backend\Template\ModuleTemplate: ~

  # Not a service, not injectable
  TYPO3\CMS\Backend\Module\ModuleInterface: ~

  TYPO3\CMS\Backend\Template\ModuleTemplateFactory:
    shared: false
    public: true

  TYPO3\CMS\Backend\History\RecordHistoryRollback:
    public: true

  TYPO3\CMS\Backend\Backend\Shortcut\ShortcutRepository:
    public: true

  TYPO3\CMS\Backend\View\AuthenticationStyleInformation:
    public: true

  TYPO3\CMS\Backend\Search\LiveSearch\SearchProviderRegistry:
    arguments:
      - !tagged_iterator livesearch.provider

  TYPO3\CMS\Backend\Search\LiveSearch\DatabaseRecordProvider:
    tags:
      - { name: 'livesearch.provider', priority: 50 }

  TYPO3\CMS\Backend\Search\LiveSearch\PageRecordProvider:
    tags:
      - { name: 'livesearch.provider', priority: 60 }

  TYPO3\CMS\Backend\Form\FormDataProvider\ReturnUrl:
    public: true

  TYPO3\CMS\Backend\Form\FormDataProvider\SiteDatabaseEditRow:
    public: true

  TYPO3\CMS\Backend\Form\InlineStackProcessor:
    shared: false

  TYPO3\CMS\Backend\Form\Processor\SelectItemProcessor:
    public: true

  TYPO3\CMS\Backend\RecordList\DatabaseRecordList:
    shared: false
    public: true

  TYPO3\CMS\Backend\RecordList\ElementBrowserRecordList:
    shared: false
    public: true

  TYPO3\CMS\Backend\ElementBrowser\DatabaseBrowser:
    shared: false

  TYPO3\CMS\Backend\ElementBrowser\ElementBrowserRegistry:
    arguments:
      - !tagged_iterator recordlist.elementbrowser

  TYPO3\CMS\Backend\Resource\PublicUrlPrefixer:
    public: true

  TYPO3\CMS\Backend\Backend\ToolbarItems\ClearCacheToolbarItem:
    public: true

  TYPO3\CMS\Backend\Backend\ToolbarItems\ShortcutToolbarItem:
    public: true

  TYPO3\CMS\Backend\Backend\ToolbarItems\SystemInformationToolbarItem:
    public: true

  TYPO3\CMS\Backend\LinkHandler\RecordLinkHandler:
    shared: false
    public: true

  TYPO3\CMS\Backend\Tree\View\ContentCreationPagePositionMap:
    public: true

  TYPO3\CMS\Backend\Tree\View\ContentMovingPagePositionMap:
    public: true

  TYPO3\CMS\Backend\Security\SudoMode\Access\AccessFactory:
    public: true

  TYPO3\CMS\Backend\Security\SudoMode\Access\AccessStorage:
    public: true

  TYPO3\CMS\Backend\View\RecordSearchBoxComponent:
    shared: false
    public: true

  # Toolbar registry
  TYPO3\CMS\Backend\Toolbar\ToolbarItemsRegistry:
    arguments:
      - !tagged_iterator backend.toolbar.item
