services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TYPO3\CMS\Tstemplate\:
    resource: '../Classes/*'

  TYPO3\CMS\Tstemplate\Hooks\DataHandlerClearCachePostProcHook:
    public: true

  TYPO3\CMS\Tstemplate\Controller\ConstantEditorController:
    tags: [ 'backend.controller' ]

  TYPO3\CMS\Tstemplate\Controller\InfoModifyController:
    tags: [ 'backend.controller' ]

  TYPO3\CMS\Tstemplate\Controller\ObjectBrowserController:
    tags: [ 'backend.controller' ]

  TYPO3\CMS\Tstemplate\Controller\TemplateAnalyzerController:
    tags: [ 'backend.controller' ]

  TYPO3\CMS\Tstemplate\Controller\TemplateRecordsOverviewController:
    tags: [ 'backend.controller' ]
