# This is the project specific Settings.yml file.
# Place Sphinx specific build information here.
# Settings given here will replace the settings of 'conf.py'.

---
conf.py:
  copyright: 1997-2013
  project: User>Task Center, Actions
  version: 6.2
  release: 6.2
...
