services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TYPO3\CMS\Recycler\:
    resource: '../Classes/*'
    # Tasks require EXT:scheduler to be installed, ignore for now.
    exclude: '../Classes/Task'

  TYPO3\CMS\Recycler\Controller\RecyclerModuleController:
    tags: [ 'backend.controller' ]
